export default [
  {
    name: "first_name",
    label: "Имя",
    initValue: "",
    type: "text",
    required: true,
    maxLength: 256,
  },
  {
    name: "last_name",
    label: "Фамилия",
    initValue: "",
    type: "text",
    required: true,
    maxLength: 256,
  },
  {
    name: "birth_date",
    label: "Дата рождения",
    initValue: "",
    type: "date",
    required: true,
    maxLength: 256,
    format: "YYYY-MM-DD",
  },
  {
    name: "gender",
    label: "Пол",
    initValue: "",
    type: "select",
    options: [
      { value: "male", label: "мужчина" },
      { value: "female", label: "женщина" },
    ],
    required: true,
  },
  {
    name: "job",
    label: "Професия",
    initValue: "",
    type: "text",
    required: true,
    maxLength: 256,
  },
  {
    name: "biography",
    label: "Биография",
    initValue: "",
    type: "textarea",
    required: true,
    maxLength: 1024,
  },
  {
    name: "is_active",
    label: "Активен",
    initValue: false,
    type: "checkbox",
    required: false,
  },
];
